config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener'

  get '/users', to: 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy], shallow: true
      resources :likes, only: [:create]
    end
  end
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy', as: 'user_post_comment'
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index show create] do
        resources :posts, only: %i[index show create] do
          resources :comments, only: %i[index show create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  has_many :posts, foreign_key: 'author_id', inverse_of: :author, dependent: :destroy
  has_many :likes, foreign_key: 'author_id', inverse_of: :author, dependent: :destroy
  has_many :comments, foreign_key: 'author_id', inverse_of: :author, dependent: :destroy

  def recent_posts()
    posts.order(created_at: :desc).limit(3)
  end

  ROLES = %i[admin user].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      before_action :set_user

      def index
        render json: @user.posts
      end

      private

      def set_user
        @user = User.find(params[:id])
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div>
<% @users.each do |user| %>
<section class="h-full">
  <a class="rounded-lg p-8 flex items-center h-full m-1" href="<%= user_path(user.id) %>">  
    <img class="user-avatar border" src="<%= user.photo %>">
    <div class="border w-full h-36 ml-4">
        <h2 class="font-bold ml-4 mt-4 header-font"><%= user.name %></h2>
    <div class="flex justify-end">
        <p class="text-red-600 mt-16 mr-2">Number of posts: <%= user.posts_counter %></p>
        </div>
    </div>
  </a>
    <!-- display user's posts, comments, likes, etc. -->
</section>
<% end %>
</div>

app/views/users/show.html.erb
<div class="m-4" style="display:flex; flex-direction:column; align-items:stretch; row-gap:2vh">
<section class="rounded-lg p-2 flex items-center">
    <img class="border" src="<%= @user.photo %>">
    <div class="border w-full h-36 ml-4">
        <h2 class="font-bold ml-4 mt-4 header-font"><%= @user.name %></h2>
    <div class="flex justify-end">
        <p class="text-red-600 mt-16 mr-2">Number of posts: <%= @user.posts_counter %></p>
        </div>
    </div>
    <!-- display user's posts, comments, likes, etc. -->
</section>
<section class="rounded-lg border p-8 items-center">
        <h3 class="font-bold">Bio</h3>
        <p class="mt-4">
        <%= @user.bio %>
        </p>
</section>
<% @user.recent_posts.each do |post| %>
<section class="rounded-lg p-8 items-center border">
    <h3 class="font-bold">Post #<%= post.id %></h3>
        <h3 class="mt-4 text-blue-900"> <%= post.title %> </h3>
        <p class="mt-4"><%= post.text %></p>
    <h5 class="text-red-900 font-bold mt-4 text-right"> comments: <%= post.comments_counter %>, likes: <%= post.likes_counter %></h5>
    <!-- display user's posts, comments, likes, etc. -->
</section>
<% end %>
<a href="<%= user_posts_path(@user) %>">
<button class="border p-6 font-bold" style="width:30%; margin-left:40%;">See all posts</button>
</a>
</div>