config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener'

  get '/users', to: 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy], shallow: true
      resources :likes, only: [:create]
    end
  end
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy', as: 'user_post_comment'
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index show create] do
        resources :posts, only: %i[index show create] do
          resources :comments, only: %i[index show create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_destroy :decrease_counter
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :likes, inverse_of: 'post', dependent: :destroy
  has_many :comments, inverse_of: 'post', dependent: :destroy

  after_save -> { author.increment!(:posts_counter) }
  before_destroy :decrease_counter

  def update_counter
    author.increment!(:posts_counter)
  end

  def decrease_counter
    author.decrement!(:posts_counter)
  end

  def recent_comments()
    comments.limit(5).order(created_at: :desc)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      before_action :set_user
      before_action :set_post, only: %i[comments add_comment]

      def index
        @posts = Post.all
        render json: @posts
      end

      private

      def set_user
        @user = User.find(params[:user_id])
      end

      def set_post
        @post = @user.posts.find(params[:id])
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def show
    @post = Post.includes(:comments, :likes).where(author_id: params[:user_id]).find(params[:id])
    authorize! :read, @post
    @user = User.find(params[:user_id])
    new_comment = Comment.new
    new_like = Like.new
    respond_to do |format|
      format.html { render :show, locals: { new_comment:, new_like: } }
    end
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post

    # Delete all comments associated with this post
    @post.comments.delete_all

    # Delete all likes associated with this post
    @post.likes.delete_all

    # Finally, delete the post itself
    @post.destroy

    redirect_to user_path(current_user)
  end

  def create
    post_params = params.require(:post).permit(:title, :text)
    @post = current_user.posts.build(post_params)

    respond_to do |_format|
      if @post.save
        flash[:notice] = 'Post created successfully'
        redirect_to users_path
      else
        Rails.logger.error(@post.errors.full_messages)
        flash.now[:alert] = 'Post creation failed'
        render :new, locals: { post: @post }
      end
    end
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="m-4" style="display:flex; flex-direction:column; align-items:stretch; row-gap:2vh">
<section class="rounded-lg p-2 flex items-center">
    <img class="border" src="<%= @user.photo %>">
   <div class="border w-full h-36 ml-4">
        <h2 class="font-bold ml-4 mt-4 header-font"><%= @user.name %></h2>
    <div class="flex justify-end">
        <p class="text-red-600 mt-16 mr-2">Available Number of posts: <%= @user.posts_counter %></p>
        </div>
    </div>
</section>
<% @posts.each do |post| %>
<a href="<%= user_post_path(@user, post) %>">
    <div class="rounded-lg p-8 items-center border">
        <h3 class="font-bold">Post #<%= post.id %>: <%= post.title %></h3>
        <p class="mt-4"><%= post.text %> <%= post.recent_comments.length %></p>
        <h5 class="text-red-900 font-bold mt-4 text-right"> comments: <%= post.comments_counter %>, likes: <%= post.likes_counter %></h5>
    </div>
    </a>
  <% if post.recent_comments.any? %>
        <div class="border">
      <% post.recent_comments.each do |comment| %>
          <p class="font-bold"  style="padding: 1rem"> <%= comment.author.name %>: <%= comment.text %> <p>
      <% end %>
        </div>
    <% end %>
     <% end %>
     <button class="border p-6 font-bold mb-4" style="width:25%; margin-left:40%;">pagination</button>
</div>

app/views/posts/new.html.erb
<ul class="ul-box">
  <li class="li-box">
    <h2>Create a New Post For you</h2>
  </li>
  <li class="li-box">
    <%= form_with model: @post, url: user_posts_path do |form| %>
      <div>
        <%= form.text_field :title, placeholder: 'Enter title', required: true, class: 'form-input' %>
      </div>
      <div>
        <%= form.text_area :body, placeholder: 'Enter Post Text', required: true, class: 'form-text-area' %>
      </div>
      <%= form.submit "Create Post", class: "button form-button" %>
    <% end %>
  </li>
</ul>

app/views/posts/show.html.erb
<div class="m-4" style="display:flex; flex-direction:column; align-items:stretch; row-gap:2vh">
  <div>
    <div class="rounded-lg p-8 items-center border">
      <div class="flex justify-between">
        <h3 class="font-bold">Post #<%= @post.id %> by <%= @user.name %></h3>
        <h5 class="text-red-900 font-bold mt-4 text-right"> comments: <%= @post.comments_counter %>, likes: <%= @post.likes_counter %></h5>
      </div>
      <h3 class="mt-4 text-blue-900"> <%= @post.title %> </h3>
      <p class=""><%= @post.text %></p>
     <% if can? :destroy, @post %>
  <%= form_with model: @post, method: :delete, local: true, url: user_post_path(@user, @post), data: { confirm: "Are you sure?" }, html: {class: "row flex-end"} do |f| %>
    <%= f.submit "Delete Post", class: "auto-width bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
  <% end %>
<% end %>
    </div>

    <% if @post.recent_comments.any? %>
      <div class="border mt-4" style="padding: 2rem">
        <% @post.comments.each do |comment| %>
          <div>
            <p class="font-bold"> <%= comment.author.name %>: Comment <%= comment.id %> <p>
            <p> <%= comment.text %></p>
          </div>
          <div>
            <%= form_with model: [@user, @post.likes.build], url: user_post_likes_path(@user, @post) do |form| %>
              <%= form.hidden_field :post_id, value: @post.id %>
              <%= form.submit 'Like post', class: 'btn btn-primary bg-red-800 text-white font-bold p-2 m-2 rounded-full' %>
            <% end %> <!-- Close the form_with block here -->
            <div class="flex-center">
              <% if can? :destroy , comment %>
                <%= form_with model: comment, method: :delete, local: true, url: user_post_comment_path(@user, @post, comment), html: {class: "row flex-end"} do |f| %>
                  <%= f.submit "Delete Comment", class: "auto-width bg-black text-white p-2 m-2 rounded-full" %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>
<li class="li-box">
  <a href="<%= url_for(new_user_post_comment_path(@user, @post)) %>" class="button button-wide bg-black text-white font-bold p-2 m-2">Add Comment</a>
</li>